# action.yml
name: 'Dream Team'
description: 'Get a list of people to build a dream team'
inputs:
  number:  # id of input
    description: 'Number of players you need'
    required: true
    default: 10
outputs:
  captains-email: # id of output
    description: 'Captain of the team'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number }}
